// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMcUP_LNh3uN8kQbSoBGXYnD9ah1p-lf8',
    appId: '1:181607548486:web:5fd1e2935ca2e439c76c47',
    messagingSenderId: '181607548486',
    projectId: 'flutter-function-fcm-demo',
    authDomain: 'flutter-function-fcm-demo.firebaseapp.com',
    storageBucket: 'flutter-function-fcm-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBkg-tYE3JRwpRy16LhGuhSSavHvQ3JrU',
    appId: '1:181607548486:android:4a27aefa2b0374d2c76c47',
    messagingSenderId: '181607548486',
    projectId: 'flutter-function-fcm-demo',
    storageBucket: 'flutter-function-fcm-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHGGyysmJiy-pfA3ldePz7XT8JqK_K874',
    appId: '1:181607548486:ios:82a573356272c654c76c47',
    messagingSenderId: '181607548486',
    projectId: 'flutter-function-fcm-demo',
    storageBucket: 'flutter-function-fcm-demo.appspot.com',
    iosClientId:
        '181607548486-47q3kli3itvp90j6c9sn9l48gc041gfa.apps.googleusercontent.com',
    iosBundleId: 'au.com.calvinr.fcm.demo.demo',
  );
}
